name: flutter_sm_get_plus
description: "This is an enhanced implementation of GetX."
version: 0.0.2-preview-1
homepage: "https://github.com/shay-wong/flutter_sm_get_plus"
repository: "https://github.com/shay-wong/flutter_sm_get_plus"
issue_tracker: "https://github.com/shay-wong/flutter_sm_get_plus/issues"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^5.0.0-release-candidate-5
  loading_animation_widget: ^1.2.1
  flutter_sm_models: ^0.0.2

dependency_overrides:
  get: 5.0.0-release-candidate-5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
